apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aa-test1
resources:
#- namespace.yaml
- subscription.yaml
- operator-group.yaml
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  